# Generated by Django 4.2.2 on 2023-06-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ad_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities')], max_length=20),
        ),
    ]
