# Generated by Django 4.2.2 on 2023-06-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='message1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='message2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquire', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='message',
        ),
    ]
