# Generated by Django 4.2.2 on 2023-06-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_message1_message2_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message1',
            old_name='comment',
            new_name='comment1',
        ),
        migrations.RenameField(
            model_name='message2',
            old_name='enquire',
            new_name='enquire1',
        ),
    ]
