# Generated by Django 4.2.2 on 2023-06-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_comment_message1_comment1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message1',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message2',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
