# Generated by Django 4.2.2 on 2023-06-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_message1_id_alter_message2_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message1',
            old_name='comment1',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='message2',
            old_name='enquire1',
            new_name='enquire',
        ),
    ]
